config/routes.rb
Rails.application.routes.draw do
  root to: 'landing#start'

  resources :users, only: [:new, :create, :index, :destroy] do
    resources :steps, only: [:show, :update], controller: 'user/steps'
  end

  resources :versus, only: [] do
    collection do
     get 'school_picker'
     get 'arena'
     get 'summary'
    end
  end

end

app/controllers/versus_controller.rb
class VersusController < ApplicationController
  before_filter :set_user
  before_filter :set_schools, only: [:arena, :summary]
  before_filter :calculate_preferences, only: [:arena, :summary]

  def school_picker
    @schools = School.all
  end

  def arena
    # round1 = season, zip
    # round2 = location_type (urban, rural, etc.), school_size (small, medium, large)
    # round3 = sport_acedemic_balance
  end

  def summary
    calculate_final_result
    @attrs = attribute_values
    @coaches = CollegeSportCoach.where(sport_id: @user.sport_id, school_id: [@my_school.id, @opp_school.id])
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_schools
    @my_school = School.find(params[:my_school_id])
    @opp_school = School.find(params[:opp_school_id])
  end

  def calculate_preferences
    @result = case params[:round_number]
              when '1'
                  calculate_round1_result
              when '2'
                calculate_round2_result
              when '3'
                calculate_round3_result
              end
  end

  def calculate_round1_result
    season_result = compare_choices(:season)
    zip_result = compare_zips
    print_result(season_result + zip_result)
  end

  def calculate_round2_result
    location_type_result = compare_choices(:location_type)
    school_size_result = compare_choices(:school_size)
    print_result(location_type_result + school_size_result)
  end

  def calculate_round3_result
    print_result(compare_choices(:sport_acedemic_balance) * 2) # only one result to calculate
  end

  def compare_choices(attribute)
    my_choice = @user[attribute]
    my_school_result = @my_school.preferences[attribute]
    opp_school_result = @opp_school.preferences[attribute]

    if my_choice == my_school_result && my_choice != opp_school_result
      2 # win
    elsif my_choice == opp_school_result && my_choice != my_school_result
      0 # loss
    else
      1 # draw
    end
  end

  def compare_zips
    distance1 = @user.distance_from(@my_school.coordinates)
    distance2 = @user.distance_from(@opp_school.coordinates)
    distance1 < distance2 ? 2 : 0
  end

  def print_result(points)
    if points >= 3
      2
    elsif points <= 1
      0
    else
      1
    end
  end

  def calculate_final_result
    total_points = calculate_round1_result + calculate_round2_result + calculate_round3_result
    @final_result_message = if total_points >= 4
                              "Your mascot won! Looks like #{@my_school.name} is the better fit for you."
                            elsif total_points <= 2
                              "Your mascot lost! Looks like #{@opp_school.name} is the better fit for you."
                            else
                              'The mascots fought to a draw. Both these schools are a good match for you!'
                            end
  end

  def attribute_values
    [@my_school, @opp_school].map do |school|
      attrs = Hash.new
      attrs['Proximity'] = "#{@user.distance_from(school.coordinates).to_i} miles"
      attrs['Weather Type'] = SchoolPreferenceMap::SEASONS[school.preferences.season]
      attrs['School Size'] = SchoolPreferenceMap::SIZE[school.preferences.school_size]
      attrs['Location Type'] = SchoolPreferenceMap::LOCATION_TYPE[school.preferences.location_type]
      attrs['Sport Academic Balance'] = SchoolPreferenceMap::S_A_BALANCE[school.preferences.sport_acedemic_balance]
      attrs
    end
  end
end

app/helpers/versus_helper.rb
module VersusHelper
end

app/views/versus/arena.html.erb
<section class="arena">

  <div class="container">

    <div>Round <%= params[:round_number] %></div>
      <div id="canvasDiv"></div>

    <script type="text/javascript">
      var arena = new Arena(document.getElementById("canvasDiv"), 960, 500, <%= params[:user_id] %>, <%= params[:my_school_id] %>, <%= params[:opp_school_id] %>, <%= @my_school.ipeds_id %>, <%= @opp_school.ipeds_id %>, <%= params[:round_number] %>, <%= @result %> );
    </script>

  </div>
</section>

app/views/versus/school_picker.html.slim
section
  .container

    h2 Player Select

    h3 Choose Your School

    .school-container.group
      - School.all.each do |school|
        - working_ipeds = [170976, 155681, 238430, 110680, 175616]
        - possible_ipeds = working_ipeds - [school.ipeds_id]
        - opp_school_id = School.find_by(ipeds_id: possible_ipeds.sample).id
        - class_names = 'school'
        - class_names += ' disabled' unless working_ipeds.include?(school.ipeds_id)
        = link_to arena_versus_path, class: class_names, data: { user_id: @user.id, opp_school_id: opp_school_id, my_school_id: school.id } do
          = image_tag school.logo, class: 'logo'

app/views/versus/summary.html.erb
<section>
    <div class="container">

      <h2 class="message"><%= @final_result_message %></h2>

      <div class="summary">

        <div class="half">

          <h3><%= @my_school.name %></h3>
          <% @attrs[0].each do |k, v| %>
            <div><%= "#{k}: #{v}" %></div>
            </br>
          <% end %>

        </div>

        <div class="half">

          <h3><%= @opp_school.name %></h3>
            <% @attrs[1].each do |k, v| %>
              <div><%= "#{k}: #{v}" %></div>
              </br>
          <% end %>

        </div>

        <div class="clearfix"></div>

        <h3 class="back-to-school"><%= link_to 'Challenge a New School', school_picker_versus_path(user_id: @user.id) %></h3>

        <h4 id="coach-js">Coaches at These Schools for Your Sport</h4>
        <div id="coach-info-js">
          <ul>
            <% @coaches.each do |coach| %>
              <li><%= coach.coach_name %>, <%= coach.coach_position%> (<%= coach.college_name %>)</li>
            <% end %>
          </ul>
        </div>

      </div>

    </div>
</section>

<script>
  $(document).ready(function() {
    $( "#coach-js" ).click(function() {
      $( "#coach-info-js" ).show(200);
    });
  });
</script>